# Etapa 1: build
FROM node:22-alpine AS builder

# Instalar pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

# Copiamos manifest primero para aprovechar la cache
COPY package.json pnpm-lock.yaml* ./

# Instalamos dependencias (sin dev opcional si quieres más liviano en prod)
RUN pnpm install --frozen-lockfile

# Copiamos el resto del código
COPY . .

# Build de la app NestJS
RUN pnpm build


# Etapa 2: runtime
FROM node:22-alpine AS runner

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

# Copiamos solo lo necesario para runtime
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --prod --frozen-lockfile

# Copiamos el dist generado en la etapa de build
COPY --from=builder /app/dist ./dist

# Exponer el puerto NestJS (normalmente 3000, ajusta si tu app usa otro)
EXPOSE 3000

# Comando de inicio
CMD ["node", "dist/main"]
