name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
      - "feature/**"
      - "ECO-51-integracion-CI/CD"
    #Solo se ejecuta si hay cambios en la carpeta Frontend/
    paths:
      - "Frontend/**"

  pull_request:
    branches:
      - main
    paths:
      - "Frontend/**"

jobs:
  # JOB 1: CI (Quality Checks, Tests, and Build)
  ci_quality_checks:
    runs-on: ubuntu-latest

    # Define el directorio de trabajo donde está el package.json
    defaults:
      run:
        working-directory: ./Frontend

    steps:
      - name: Checkout del Código
        uses: actions/checkout@v4

      - name: Configurar Node.js (Versión 20)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalación de Dependencias
        run: npm install

      - name: Ejecutar Verificación de Formato y Linting
        run: |
          npm run format -- --check
          npm run lint

      - name: Ejecutar Pruebas Unitarias
        run: npm run test

      - name: Crear Artefacto de Producción (Build)
        run: npm run build

      - name: Subir Artefacto de Build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-artifact
          path: ./Frontend/dist

  # JOB 2: CD (Deployment a Firebase Hosting)
  cd_deployment:
    needs: ci_quality_checks
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production # Se recomienda usar un entorno de despliegue

    steps:
      - name: Checkout del Código
        uses: actions/checkout@v4

      # 1. Descargar el Artefacto (Archivos estáticos 'dist')
      - name: Descargar Artefacto de Build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build-artifact
          path: ./dist

      # 2. Despliegue a Firebase Hosting
      - name: Despliegue del Frontend a Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          # CRÍTICO: Usa el Secret que contiene las credenciales de Firebase
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOKEN }}"
          projectId: frontend-ordenes-cliente
          channelId: live
